import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import OfferNav from "@/components/navbar/OfferNav";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ModeToggle } from "@/components/buttons/ThemeButton";
import MainNav from "@/components/navbar/MainNav";
import MainFooter from "@/components/footers/MainFooter";
import NewLetterForm from "@/components/forms/NewLetterForm";
import CartSidebar from "@/components/sidebar/CartSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`antialiased ${poppins.className}`}
      >
        <ThemeProvider>
          <OfferNav />
          <MainNav />
          {children}
          <CartSidebar />
          <ModeToggle />
          <NewLetterForm />
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
